[QuartzNet]
=#R3vOLuTioN*http://r3volution2.altervista.org/scripts.php*1 Mix*public
[ChLame]
=ChLame*irc.chlame.net*http://chlame.net
=#universal*http://plugin*1 Mix*restricted
=#HANTARUS*http://plugin*1 Mix*restricted
=#PoWell*http://176.31.190.185/scripts.php*1 Mix*public
=#NEW-WORLD*http://plugin*1 Mix*restricted
=#Movida*http://plugin*1 Mix*restricted
=#INFINITY*http://www.infinity.wklm.it/scripts.php*1 Mix*public
[OltreIrc]
=OltreIrc*irc.oltreirc.net*http://.oltreirc.net
=#ElDoRaDo*http://plugin*1 Mix*restricted
=#MulTiSaLa*http://plugin*1 Mix*restricted
=#MaLeFiCeNT*http://plugin*1 Mix*restricted
=#GOOGLE*http://178.33.239.145/Lista_google/scripts.php*1 Mix*public
[explosionirc.net]
=explosionirc.net*irc.explosionirc.net*http://.explosionirc.net
=#RELOADED*http://plugin*1 Mix*restricted